[package]
name = "file_uploader_core"
version.workspace = true
authors.workspace = true
edition = "2024"

[dependencies]
tracing = {workspace = true}
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
chrono = {workspace = true}
file_uploader_sdk = {workspace = true}
stabby = {workspace = true}
libloading = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
file_uploader_plugins = {workspace = true}
